// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import FormFieldStateController from "./form_field_state_controller"
application.register("form-field-state", FormFieldStateController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PopulateInputController from "./populate_input_controller"
application.register("populate-input", PopulateInputController)
